//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking_Tbl
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "CustomerId is Mandatory")]
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Executive_Id { get; set; }

        [Required(ErrorMessage = "Please Select Date")]
        public string Date { get; set; }

        [Required(ErrorMessage = "Please Choose Time")]
        public string Time { get; set; }

        [Required(ErrorMessage = "Weight cannot be empty")]
        public Nullable<double> Weight { get; set; }

        public Nullable<double> Price { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
