//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer_Tbl
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        public string Name { get; set; }    //-------------Name----------------------------------------
        /// </summary>

        [Required(ErrorMessage = "This Field is required")]
        public Nullable<int> Age { get; set; } //-------------Age----------------------------------------

        [Required(ErrorMessage = "This Field is required")]
        public string Address { get; set; }     //-------------Address----------------------------------------

        [Required(ErrorMessage = "Enter Password")]
        public string Password { get; set; } //-------------Password----------------------------------------

        [Required(ErrorMessage = "Enter Password")]
        [Compare("Password",ErrorMessage ="Password Do not Matched")]
        public string ConfirPassword { get; set; }//-------------Confirm Password----------------------------------------

        [Required(ErrorMessage = "Enter Email")]
        //[RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z",
                            //ErrorMessage = "Please Enter a valid email address")]
        public string Email { get; set; }   //-------------Email----------------------------------------

    }
}
