//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project_DBEntities1 : DbContext
    {
        public project_DBEntities1()
            : base("name=project_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Tbl> Booking_Tbl { get; set; }
        public virtual DbSet<Customer_Tbl> Customer_Tbl { get; set; }
        public virtual DbSet<Executive_Tbl> Executive_Tbl { get; set; }
    }
}
